ruleset=🎯 全球直连,https://raw.githubusercontent.com/onlyrzc/oc/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/onlyrzc/oc/refs/heads/main/ProxyLite.list
ruleset=✨ AI,https://raw.githubusercontent.com/onlyrzc/oc/refs/heads/main/AI.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=👌 $,https://raw.githubusercontent.com/onlyrzc/oc/refs/heads/main/DD.list
ruleset=📘 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list 
ruleset=🪂 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list 
ruleset=🙋 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list 
ruleset=🕊️ Twitter(X),https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list 
ruleset=💁 WhatsApp,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list 
ruleset=🗣️ Facebook,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list 
ruleset=🌳 Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list 
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list 
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list 
ruleset=🔍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list 
ruleset=🎮 Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list 
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list 
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list 
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list 
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list 
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list 
ruleset=🎞️ YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list 
ruleset=📺 Disney,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list 
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list 
ruleset=🎬 HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list 
ruleset=🎵 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list 
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list 
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list 
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
custom_proxy_group=🚀 节点选择`select`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🎯 全球直连`select`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=✨ AI`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=📘 GitHub`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🪂 TikTok`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🙋 Telegram`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🕊️ Twitter(X)`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=💁 WhatsApp`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🗣️ Facebook`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🌳 Amazon`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🍎 Apple`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=Ⓜ️ Microsoft`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🔍 Google`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🎮 Steam`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🕹️ Game`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🎞️ YouTube`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=📺 Disney`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🎥 Netflix`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🎬 HBO`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🎵 Spotify`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=👌 $`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🌍 国外`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `
custom_proxy_group=🐟 漏网之鱼`selectselect`[]🚀 节点选择[]🇭🇰 香港节点[]🇹🇼 台湾节点[]🇸🇬 新加坡节点[]🇯🇵 日本节点[]🇺🇲 美国节点[]🇰🇷 韩国节点[]DIRECT`.* `

custom_proxy_group=🇭🇰 香港节点`url-test`港|HK|Hong Kong`http://www.gstatic.com/generate_204`180,5,100 
custom_proxy_group=🇯🇵 日本节点`url-test`日|JP|Japan`http://www.gstatic.com/generate_204`180,5,100 
custom_proxy_group=🇺🇲 美国节点`url-test`美|US|United States`http://www.gstatic.com/generate_204`180,5,100 
custom_proxy_group=🇹🇼 台湾节点`url-test`台|TW|Taiwan`http://www.gstatic.com/generate_204`180,5,100 
custom_proxy_group=🇸🇬 新加坡节点`url-test`新|SG|Singapore`http://www.gstatic.com/generate_204`180,5,100 
custom_proxy_group=🇰🇷 韩国节点`url-test`韩|KR|Korea`http://www.gstatic.com/generate_204`180,5,100 
;4、启用规则集 
enable_rule_generator=true 
overwrite_original_rules=true 